// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqh0DP8l9bbs1IxLMOGpQRbZiLPRv5dQ0',
    appId: '1:584243675913:web:fc97eb68de9416ab8b89d8',
    messagingSenderId: '584243675913',
    projectId: 'flutter-streaming-music',
    authDomain: 'flutter-streaming-music.firebaseapp.com',
    storageBucket: 'flutter-streaming-music.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbrSZ_jDdmuWPunikvE9358Q3lRbzUPt8',
    appId: '1:584243675913:android:409dec3156f2eebd8b89d8',
    messagingSenderId: '584243675913',
    projectId: 'flutter-streaming-music',
    storageBucket: 'flutter-streaming-music.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQQMKQ4uowduAoj_3RTmnkiUfRTL459L8',
    appId: '1:584243675913:ios:05ca296148cdbc878b89d8',
    messagingSenderId: '584243675913',
    projectId: 'flutter-streaming-music',
    storageBucket: 'flutter-streaming-music.appspot.com',
    iosBundleId: 'com.example.flutterSpotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqh0DP8l9bbs1IxLMOGpQRbZiLPRv5dQ0',
    appId: '1:584243675913:web:c73e115b013631168b89d8',
    messagingSenderId: '584243675913',
    projectId: 'flutter-streaming-music',
    authDomain: 'flutter-streaming-music.firebaseapp.com',
    storageBucket: 'flutter-streaming-music.appspot.com',
  );
}
